### ISSUE TITLE
Port is static at 5000

### ISSUE THREAD

**Issue by nitsuga5124** [prgress/dashcord#1]
The network port is currently static at 5000, this may interfere with other applications. It should be possible to customize it.

**Comment by SpyrosRoum** [comment]
I think You can actually customize it, it just always prints that it is on port 5000

**Comment by MM-coder** [comment]
You can customize it by editing the `application.py` file

**Comment by lganWebb** [comment]
You actually don’t need any library modifications to do this. Just supply `dashcord.App(...).start(host, port)` with your host (e.g "localhost") and port (e.g 5000)
